### ISSUE TITLE
About Time Zone

### ISSUE THREAD

**Issue by jecanac474** [hykilpikonna/blog-data#2]
I hope to include instructions on how to change the time zone of the generation time in the README file, as follows:

If you need to change the time zone of the generated time, you can add the following information to the tgcyml file. You can click on [this link](https://github.com/jecanac474/blog-data/blob/main/.github/workflows/tgc.yml) to see an example of using Asia/Shanghai time zone.

```
env:
  TZ: Asia/Shanghai
  LC_TIME: POSIX
```

RAW:
``````
If you need to change the time zone of the generated time, you can add the following information to the tgcyml file. You can click on [this link](https://github.com/jecanac474/blog-data/blob/main/.github/workflows/tgc.yml) to see an example of using Asia/Shanghai time zone.

```
env:
  TZ: Asia/Shanghai
  LC_TIME: POSIX
```
``````

**Comment by hykilpikonna** [comment]
Thanks! added.
